### **Ridge Lasso Elasticnet**

In [1]:
# Ridge Lasso ve Elasticnet lineer regresyon metotları 

#### Import ve Data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("boston.csv")
df.head(3)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
2  392.83   4.03   34.7

In [4]:
X = df.drop("PRICE", axis=1)
y = df["PRICE"]

#### **Polinom Dönüşüm**

In [5]:
from sklearn.preprocessing import PolynomialFeatures

poly_conv = PolynomialFeatures(degree=2, include_bias= False)

X_poly = poly_conv.fit_transform(X)

#### **Train Test Split**

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=99)  

#### **Standart Scaler**

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
# Veriyi ölçeklendireceğiz
# Verilerin ortalaması 0 standart sapması 1 oluyor

In [10]:
scaler = StandardScaler()

In [11]:
# Aşşğıdaki mantık şu hani teste niye fit yazmadık diye normalde zaten train verimizi biz fit edip transform ediyorduk fit_transform oluyordu test verimize gerek yok

In [12]:
scaler.fit(X_train)

StandardScaler()

In [13]:
X_train = scaler.transform(X_train)

In [14]:
X_test = scaler.transform(X_test)

In [15]:
X_train.shape

(354, 13)

### **Ridge Regression**

In [ ]:
# Ridge regresyonda amaç low variance, low bias a ulaşmak varianca (ayrılmak saçılmak), bias ise hata payı istediğimiz yerden uzaklığı gibi
# High Variance = Overfitting
# High Bias = Underfitting


# Ridge de Lasso da veriye penaltı ekliyor bunu niye ve nasıl yapıyor :

# Mantık şu bizim train verilerimizle test verilerimizin farkına bakıyor ve daha doğru bir model oluşturabilmek için train verilerimizle test verilerimizin farkına bakarak bir penaltı oluşturuyor ve o penaltıya göre daha doğru bir doğru oturtur


# Ridge ve Lasso Arasındaki Fark
# Ridge = ( Ceza Parametresi ) ** 2
# Lasso = |Ceza Parametresi| 
# Biri Ceza parametresinin karesi diğeri mutlak değeri



# Ridge   = (MSE) + alpha * (CezaPara ** 2)
# MSE : MeanSquaredError 
# Lasso   = (MSE) + alpha * |Ceza Para|

# Buradaki alpha(lambda işareti de olabilir) bizim coefficientlarımızın (katsayılarımızın) toplamı
# Yine de hatırlatayım

# Coefficient : Bizim modelimizdeki featureslar örn:(Boy, Kilo) bunların tahmin etmek istediğimiz şeyi örn:(hastahaneye gitme) `nin belirlenmesinde ne kadar etkili olduğu ne kadar baskın olduğu





In [17]:
from sklearn.linear_model import Ridge

In [18]:
ridge_model = Ridge(alpha=10)
# Bunun içindeki alphayı bizim ceza(Penaltı) parametremiz gibi düşünebiliriz

In [19]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [20]:
ridge_pred = ridge_model.predict(X_test)

In [21]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [22]:
print("R2 Score: ", round(r2_score(y_test, ridge_pred),2))
print("RMSE: ", round(mean_squared_error(y_test, ridge_pred),2))
print("MAE : ", round(mean_absolute_error(y_test, ridge_pred),2))

# Kötü bir sonuç çıktı 
# 1 : Alphayı yanlış belirlemişizdir çok etkilemiştir
# 3 : 

R2 Score:  0.68
RMSE:  27.49
MAE :  3.53


#### **Alpha Değeri İçin**

In [23]:
from sklearn.linear_model import RidgeCV

In [24]:
ridge_cv = RidgeCV(alphas = (0.001, 0.01, 0.1, 1, 10),scoring="neg_mean_absolute_error") 

In [25]:
ridge_cv.fit(X_train, y_train)

RidgeCV(alphas=(0.001, 0.01, 0.1, 1, 10), scoring='neg_mean_absolute_error')

In [26]:
ridge_cv.alpha_

10.0

In [27]:
ridge_cv.coef_

# Kullanmadığı coefleri(katsayı) çok daha düşük seviylere çekti

array([-0.94316488,  1.10951924, -0.08022049,  0.57488355, -1.32939279,
        2.54395162,  0.04917646, -2.88875091,  1.88329643, -1.43625901,
       -2.07785738,  0.72288557, -4.06296246])

### **Lasso**

In [28]:
from sklearn.linear_model import LassoCV

In [29]:
lasso_cv = LassoCV(eps=0.1, n_alphas=100, cv=5)
# Burada 

In [30]:
lasso_cv.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [31]:
lasso_cv.alpha_
# Yukarıdaki kısımda bize alpha için değer bulmasını istedik Ridgde biz vermiştik

0.6851797524322562

In [32]:
lasso_cv.coef_
# Aşşağıdakilerden bazıları 0 neden? :
# Lasso bazı coeflerin işe yaramayacağını düşünerek onları 0 yapıyor 

# Ridge ise yukarıda yazdım çok daha düşük seviylere çekiyor buda ikisi arasındaki farklardan biri

array([-0.04523335,  0.        , -0.        ,  0.25112458, -0.        ,
        2.6898709 ,  0.        , -0.        , -0.        , -0.        ,
       -1.72784037,  0.20904623, -3.83924919])

In [33]:
lasso_pred = lasso_cv.predict(X_test)

In [34]:
print("R2 Score: ", round(r2_score(y_test, lasso_pred),2))
print("RMSE: ", round(mean_squared_error(y_test, lasso_pred),2))
print("MAE : ", round(mean_absolute_error(y_test, lasso_pred),2))

R2 Score:  0.63
RMSE:  31.2
MAE :  3.66


### **ElasticNet**

In [35]:
# Lasso ile Ridge in birleşmiş hali

In [36]:
from sklearn.linear_model import ElasticNetCV

In [37]:
elastic_model = ElasticNetCV(l1_ratio=(0.01,0.1,0.2,0.3,0.5,0.7,0.9,0.95,0.99,1),tol=0.01)
# Yukarıya daha detaylı bak chatten

# Şimdi yukarıda ne yazdık biz?
# l1 : Lasso
# l2 : Ridge

In [38]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=(0.01, 0.1, 0.2, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99, 1),
             tol=0.01)

In [39]:
elastic_model.l1_ratio_

0.7

In [40]:
elastic_model.coef_
# Burada coeflerin hiçbiri 0 olmadığı için Ridge regresyonu daha iyi bulup seçmiş diyebiliriz

array([-1.01032387,  1.26746194,  0.05725258,  0.52581288, -1.51774041,
        2.46693769,  0.07170637, -3.20150936,  2.36713524, -1.85998851,
       -2.12215259,  0.72755018, -4.23967722])

In [41]:
elastic_pred = elastic_model.predict(X_test)

In [42]:
print("R2 Score: ", round(r2_score(y_test, elastic_pred),2))
print("RMSE: ", round(mean_squared_error(y_test, elastic_pred),2))
print("MAE : ", round(mean_absolute_error(y_test, elastic_pred),2))

R2 Score:  0.67
RMSE:  27.71
MAE :  3.58
